version: '2'

services:
  tomcat:
    image: 'calendarapp'
    ports:
      - '8080:8080'
    environment:
      - TOMCAT_PASSWORD=123456
      - TOMCAT_ALLOW_REMOTE_MANAGEMENT=1
  main_db:
    image: mysql
    restart: always
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=123456